# -- File : Makefile.test
# -- Contents : driver for regression tests.
# -- Copyright (c) 2014-2019 Synopsys Inc.

# Path to root
THISDIR:=$(abspath $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))
PROJDIR=$(abspath $(THISDIR)/..)

# processor name
P=trv32p3

# configuration: Release, Debug, Release_LLVM, Debug_LLVM
CFG=Release
# RTL language: vlog or vhdl
HDL=vlog
# ISS executable: trv32p3_ca, trv32p3_ia, trv32p3_ia_fast
ISS=$(P)_ca_dbg
# HDL project name
H=$(P)_$(HDL)
# HDL executable
SIMV_DIR=$(PROJDIR)/hdl/$(H)
SIMV=$(SIMV_DIR)/simv
# Virtualizer model
VP_ISS=ca_tlm2_lt
# OSCI 
OSCI_ISS=$(P)_sc
OSCI_CPP_ISS=$(P)_sc_no_gui
ACCURACY=ca_tlm2_lt
FLOW=templates_flow
OSCI_EXTRA_ARGS=

# RTL variant
ifdef RTL
H:=$(H)_$(RTL)
endif

# force rerunning simulations
ifdef FORCE_RUN
RUN_DEP:=.FORCE
else
RUN_DEP:=
endif

# extra chessmk options for ISS simulate targets (chessmk -S)
CHESSMK_SIM_ARGS=

# extra chessmk options for HDL simulate targets (chessmk -H)
CHESSMK_HDL_ARGS=

# Simulate: do not check dependencies
ifdef IGNORE_DEPS
CHESSMK_SIM_ARGS+= -d
CHESSMK_HDL_ARGS+= -d
endif

# Tcl script executed by ISS
SIM_SCRIPT=$(PROJDIR)/bin/iss_rcd.tcl
SIM_SCRIPT_ARGS=

# defaults for 'run' & 'issrun' target
iss_run.$(CFG).$(ISS).log: SIM_SCRIPT_ARGS+= -disable-rcd

# diff targets: no need for report files
diff: SIM_SCRIPT_ARGS+= -no-reports
oscidiff: OSCI_EXTRA_ARGS+= -no-reports

# Debug client
V = -u verbose -u jts_verbose
V =
DBG_CLIENT=$(PROJDIR)/debug_client/$(P)_client $(V)
export LD_LIBRARY_PATH:=$(SIMV_DIR):$(LD_LIBRARY_PATH)

# Connection to the Jtalk server
J=
ifeq ($(SIMV),NONE)
JTS_PORT_NUMBER=41001
J=-u port=$(JTS_PORT_NUMBER)
endif

# Additional arguments for OCD run
ifneq ($(filter ocdrun ocddiff gdbocdrun gdbocddiff,$(MAKECMDGOALS)),)
SIM_SCRIPT_ARGS+= -simv \"$(SIMV)\"
ifdef STEP
SIM_SCRIPT_ARGS+= -step $(STEP)
endif
ifdef TMO
SIM_SCRIPT_ARGS+= -tmo \"$(TMO)\"
endif
ifdef OCD_RCD
SIM_SCRIPT_ARGS+= -rcd
endif
IGNORE_OCD_TIMEOUT=0
endif

# for coverage (ISA or RTL), set suffix for test name
CM_SUFFIX=.$(CFG).unknown
rtlrun : CM_SUFFIX=.$(CFG).rtlrun
ocdrun : CM_SUFFIX=.$(CFG).ocdrun
rtlsim : CM_SUFFIX=.$(CFG).rtlsim
export CM_SUFFIX

ifdef CODE_COV_SIMV
ocdrun : SIMV+= $(CODE_COV_SIMV) -cm_name $(notdir $(CURDIR))$(CM_SUFFIX)
endif

help:
	@ echo ""
	@ echo "    Run make as follows in one of the test directories"
	@ echo ""
	@ echo "         cd A00_report"
	@ echo "         make -f ../Makefile.test <target>"
	@ echo ""
	@ echo "    where <target> is one of the following"
	@ echo ""
	@ echo "         ok        - native execution and saving of the reference results"
	@ echo "         native    - native execution"
	@ echo "         chess     - compilation with Chess"
	@ echo "         run       - simulation of test program in ISS"
	@ echo "         diff      - check native versus ISS"
	@ echo "         rtlrun    - RTL simulation of test program"
	@ echo "         rtldiff   - check ISS versus RTL"
	@ echo "         rtlgui    - start RTL simulation of test program with GUI"
	@ echo "         rtlfree   - free running RTL simulation, no program loaded"
	@ echo "         clean     - remove intermediate files"
	@ echo "         virgin    - remove test reports"
	@ echo ""
	@ echo "    Hint: define following alias"
	@ echo "         alias mmt 'make -f ../Makefile.test  \!^ '"
	@ echo "    and execute the tests as follows"
	@ echo ""
	@ echo "         cd A00_report"
	@ echo "         mmt <target>"
	@ echo ""

# Build and run native 
native: test.gcc

# Copy test.gcc to test.ok
ok: test.ok

# Compile application
chess: $(CFG)/test

# Run on ISS
run: iss_run.$(CFG).$(ISS).log
issrun: iss_run.$(CFG).$(ISS).log

# Run on HDL simulator for N cycles (N = from ISS), generate Register Change Dump (RCD)
rtlrun: $(CFG)/test.$(H).rcd

# Run with asip2gdb
gdbrun: gdb_run.$(CFG).$(ISS).log

# Run with OCD
ocdrun: ocd_vcs_run.$(CFG).$(H).log

# Run with OCD via asip2gdb
gdbocdrun: gdb_ocd_vcs_run.$(CFG).$(H).log

# Run Tcl script driven OSCI SystemC simulation
oscirun: osci_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).log

# Run asip2gdb driven OSCI SystemC simulation
gdboscirun: gdb_osci_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).log

# Run C++ application driven OSCI SystemC simulation
oscicpprun: osci_cpp_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).log

# Run Virtualizer simulation
vprun: vprun.$(CFG).$(VP_ISS).log

# Compare ISS vs Native vs OK
diff: test.$(CFG).$(ISS).diff

# Compare ISS vs HDL, RCD traces
rtldiff: test.$(CFG).$(ISS).$(H).rtldiff

# Compare asip2gdb based ISS run vs Native vs OK
gdbdiff: test.$(CFG).$(ISS).gdbdiff

# Compare OCD based RTL sim vs Native vs OK
ocddiff: test.$(CFG).$(H).ocddiff

# Compare asip2gdb OCD based RTL sim vs Native vs OK
gdbocddiff: test.$(CFG).$(H).gdbocddiff

# Compare Tcl script driven OSCI SystemC simulation run vs Native vs OK
oscidiff: test.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).oscidiff

# Compare asip2gdb driven OSCI SystemC simulation run vs Native vs OK
gdboscidiff: test.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).gdboscidiff

# Compare C++ application driven OSCI SystemC simulation run vs Native vs OK
oscicppdiff: test.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).oscicppdiff

# Compare SystemC simulation run vs Native vs OK
vpdiff: test.$(CFG).$(VP_ISS).vpdiff

# Run on HDL simulator, setup exit breakpoint 
rtlsim: rtl_sim.$(H).log

# Run on HDL simulator, generate SAIF file
saifrun: saif_run.$(H).log

# Generate HDL testbench memory init files
hex: $(CFG)/test.PMb


# update project file
updateprx:
	@ echo "   Updating test.prx"
	@ cp ../utils/test.prx .

# native
test.gcc: test.prx test.c
	@ echo "   Compiling and running on host"
	@ chessmk -C Native test.prx    &> gcc.log
	@ chessmk -C Native test.prx -S &> test.gcc 

# update ok file (use native output)
test.ok: test.gcc
	@ sed "1,3 d" $< > $@
# remove first 3 lines: file path, compile config, run debug config

# compile
$(CFG)/test: test.prx test.c
	@ echo "   Compiling on target ($(CFG))"
	@ chessmk -C $(CFG) test.prx &> chess.$(CFG).log

# run
$(CFG)/test.$(ISS).mem: iss_run.$(CFG).$(ISS).log
iss_run.$(CFG).$(ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) ($(ISS)) - RCD disabled"
	@ chessmk -C $(CFG) test.prx -S +D $(ISS) -sim-script '$(SIM_SCRIPT) $(SIM_SCRIPT_ARGS)' $(CHESSMK_SIM_ARGS) &> $(@:%.log=%.err)
	@ echo "   (`cat $(CFG)/test.$(ISS).cycle_count` cycles)"
	@ mv $(@:%.log=%.err) $@ # on success only
	
# issrcd
$(CFG)/test.$(ISS).rcd $(CFG)/test.$(ISS).cycle_count: iss_rcd_run.$(CFG).$(ISS).log
iss_rcd_run.$(CFG).$(ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) ($(ISS)) - RCD enabled"
	@ chessmk -C $(CFG) test.prx -S +D $(ISS) -sim-script '$(SIM_SCRIPT) $(SIM_SCRIPT_ARGS)' $(CHESSMK_SIM_ARGS) &> $(@:%.log=%.err)
	@ echo "   (`cat $(CFG)/test.$(ISS).cycle_count` cycles)"
	@ mv $(@:%.log=%.err) $@ # on success only

# diff
test.$(CFG).$(ISS).diff: test.gcc $(CFG)/test.$(ISS).mem $(RUN_DEP)
	@ echo "   Checking diffs Native versus CHESS ($(CFG)) ($(ISS))"
	@ regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@
	@ tail -1 $@

# rtlrun - Generate register change dump (RCD)
$(CFG)/test.$(H).rcd: rtl_run.$(CFG).$(H).log
rtl_run.$(CFG).$(H).log: $(CFG)/test.$(ISS).cycle_count $(RUN_DEP)
	@ echo "   Simulating $(H) ($(CFG)) (`cat $(CFG)/test.$(ISS).cycle_count` cycles)"
	@ cp -f $(CFG)/test.$(ISS).cycle_count $(CFG)/test.cycle_count
	@ chessmk test.prx -H -C $(CFG) +C rcd +E $(H) +D $(P)_ca_dbg $(CHESSMK_HDL_ARGS) &> $(@:%.log=%.err)
	@ if grep -q "PDG_ASSERT" $(@:%.log=%.err); then echo "   Failed PDG assertion!"; false; fi
	@ mv $(@:%.log=%.err) $@ # on success only

# rtldiff
test.$(CFG).$(ISS).$(H).rtldiff: $(CFG)/test.$(ISS).rcd $(CFG)/test.$(H).rcd $(RUN_DEP)
	@ echo "   Checking diffs $(ISS) versus $(HDL) ($(CFG))"
	@ rcd_compare $(wordlist 1,2,$^) > $@
	@ tail -1 $@

# ocdvcsrun
$(CFG)/test.$(H).mem: ocd_vcs_run.$(CFG).$(H).log
ocd_vcs_run.$(CFG).$(H).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) ($(H)) (OCD)"
	@ $(DBG_CLIENT) -P $(PROJDIR)/lib -p $< $(J) -t "$(PROJDIR)/bin/ocd_vcs.tcl $(SIM_SCRIPT_ARGS)" &> $(@:%.log=%.err) ; exitcode=$$? ; \
	  timeout=$$(grep -s "OCD_VCS: Timeout" $(@:%.log=%.err)) ; \
	  [[ "$$timeout" != "" ]] && echo "   WARNING: OCD_VCS timeout" ; \
	  if [[ "$(IGNORE_OCD_TIMEOUT)" != 0 && "$$timeout" != "" ]] ; then \
	    exit 0 ; \
	  else \
	    exit $$exitcode ; \
	  fi
	@ mv $(@:%.log=%.err) $@ # on success only

# ocddiff
test.$(CFG).$(H).ocddiff: test.gcc $(CFG)/test.$(H).mem $(RUN_DEP)
	@ if [[ "$(IGNORE_OCD_TIMEOUT)" == 0 ]] || ! grep -q "OCD_VCS: Timeout" ocd_vcs_run.$(CFG).$(H).log ; then \
	    echo "   Checking diffs Native versus CHESS ($(CFG)) ($(H)) (OCD)" ; \
	    regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@ ; \
	    tail -1 $@ ; \
	  fi

# gdbocdrun
$(CFG)/test.$(H).gdb.mem: gdb_ocd_vcs_run.$(CFG).$(H).log
gdb_ocd_vcs_run.$(CFG).$(H).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) ($(H)) (OCD) (asip2gdb)"
	@ rm -f test.mem
	@ ( $(PROJDIR)/bin/run_with_timeout.sh -msg "OCD_VCS: Timeout" \
        $(PROJDIR)/bin/ocd/run_gdb.sh $< $(SIM_SCRIPT_ARGS) ) &> $(@:%.log=%.err) ; exitcode=$$? ; \
	  timeout=$$(grep -s "OCD_VCS: Timeout" $(@:%.log=%.err)) ; \
	  [[ "$$timeout" != "" ]] && echo "   WARNING: OCD_VCS timeout" ; \
	  if [[ "$(IGNORE_OCD_TIMEOUT)" != 0 && "$$timeout" != "" ]] ; then \
	    exit 0 ; \
	  else \
	    exit $$exitcode ; \
	  fi
	@ mv $(@:%.log=%.err) $@ # on success only

# gdbocddiff
test.$(CFG).$(H).gdbocddiff: test.gcc $(CFG)/test.$(H).gdb.mem $(RUN_DEP)
	@ if [[ "$(IGNORE_OCD_TIMEOUT)" == 0 ]] || ! grep -Eq "^OCD_VCS: Timeout" gdb_ocd_vcs_run.$(CFG).$(H).log ; then \
	    echo "   Checking diffs Native versus CHESS ($(CFG)) ($(H)) (OCD) (asip2gdb)" ; \
	    regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@ ; \
	    tail -1 $@ ; \
	  fi

# gdbrun
$(CFG)/test.$(ISS).gdb.mem: gdb_run.$(CFG).$(ISS).log
gdb_run.$(CFG).$(ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) ($(ISS)) (asip2gdb)"
	@ asip2gdb -l $(PROJDIR)/iss/$(ISS) -proc-lib $(PROJDIR)/lib -e $< < $(PROJDIR)/bin/gdbscript.txt &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@ # on success only

# gdbdiff
test.$(CFG).$(ISS).gdbdiff: test.gcc $(CFG)/test.$(ISS).gdb.mem $(RUN_DEP)
	@ echo "   Checking diffs Native versus CHESS ($(CFG)) ($(ISS)) (asip2gdb)"
	@ regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@
	@ tail -1 $@

# oscirun
$(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_ISS).mem: osci_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).log
osci_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) $(ACCURACY).$(FLOW).$(OSCI_ISS))"
	@ $(PROJDIR)/bin/sysc/run_osci.sh -iss $(OSCI_ISS) -accuracy $(ACCURACY) -flow $(FLOW) -sim-script-args "$(OSCI_EXTRA_ARGS)" $< &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@ # on success only

# oscidiff
test.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).oscidiff: test.gcc $(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_ISS).mem $(RUN_DEP)
	@ echo "   Checking diffs Native versus CHESS ($(CFG)) $(ACCURACY).$(FLOW).$(OSCI_ISS))"
	@ regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@
	@ tail -1 $@

# gdboscirun
$(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_ISS).gdb.mem: gdb_osci_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).log
gdb_osci_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) $(ACCURACY).$(FLOW).$(OSCI_ISS)) (asip2gdb)"
	@ $(PROJDIR)/bin/sysc/run_osci.sh -asip2gdb -iss $(OSCI_ISS) -accuracy $(ACCURACY) -flow $(FLOW) $< &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@ # on success only

# gdboscidiff
test.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_ISS).gdboscidiff: test.gcc $(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_ISS).gdb.mem $(RUN_DEP)
	@ echo "   Checking diffs Native versus CHESS ($(CFG)) $(ACCURACY).$(FLOW).$(OSCI_ISS)) (asip2gdb)"
	@ regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@
	@ tail -1 $@

# oscicpprun
$(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).cpp.mem: osci_cpp_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).log
osci_cpp_run.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) $(ACCURACY).$(FLOW).$(OSCI_CPP_ISS)) (C++ driven)"
	@ $(PROJDIR)/osci/$(ACCURACY)/$(FLOW)/$(OSCI_CPP_ISS) $< $(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).cpp.mem &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@ # on success only

# oscicppdiff
test.$(CFG).$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).oscicppdiff: test.gcc $(CFG)/test.$(ACCURACY).$(FLOW).$(OSCI_CPP_ISS).cpp.mem $(RUN_DEP)
	@ echo "   Checking diffs Native versus CHESS ($(CFG)) $(ACCURACY).$(FLOW).$(OSCI_CPP_ISS)) (C++ driven)"
	@ regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@
	@ tail -1 $@

# vprun
$(CFG)/test.$(VP_ISS).mem: vprun.$(CFG).$(VP_ISS).log
vprun.$(CFG).$(VP_ISS).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating on target ($(CFG)) ($(VP_ISS))"
	@ $(PROJDIR)/bin/vp/run.sh $(VP_ISS) $< &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@ # on success only

# vpdiff
test.$(CFG).$(VP_ISS).vpdiff: test.gcc $(CFG)/test.$(VP_ISS).mem $(RUN_DEP)
	@ echo "   Checking diffs Native versus CHESS ($(CFG)) ($(VP_ISS))"
	@ regression_compare --v2 test.ok $(wordlist 1,2,$^) > $@
	@ tail -1 $@


# saifrun
saif_run.$(H).log: $(CFG)/test $(RUN_DEP)
	@ echo "   Simulating $(H) ($(CFG)) (SAIF)"
	@ chessmk test.prx -H -C $(CFG) +C saif +E $(H) +D $(P)_ca_dbg $(CHESSMK_HDL_ARGS) &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@ # on success only

# rtlsim - Run RTL sim with stop condition {PC == exit address}
rtl_sim.$(H).log: $(CFG)/test
	@ echo "   Simulating $(H) ($(CFG))"
	@ chessmk test.prx -H -C $(CFG) +C rtlsim +E $(H) +D $(P)_ca_dbg $(CHESSMK_HDL_ARGS) &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@
	

# hex
$(CFG)/test.PMb $(CFG)/test.exit: hex.$(CFG).log
hex.$(CFG).log: $(CFG)/test
	@ echo "   Creating memory hex files for simulator ($(CFG))"
	@ chessmk -C $(CFG) +H test.prx $(CHESSMK_HDL_ARGS) &> $(@:%.log=%.err)
	@ mv $(@:%.log=%.err) $@

genexitfile: $(CFG)/test.exit


# To debug a test in VCS/DVE
rtlgui: $(CFG)/test.PMb
	@ echo "   Running simv with DVE"
	@ chessmk test.prx -H -C $(CFG) +C dve +E $(H) +D $(P)_ca_dbg $(CHESSMK_HDL_ARGS)

# start VCS/DVE free-running (no register log, no program load)
rtlfree:
	@ echo /dev/null > rcdname.cfg
	@ echo "   Running simv"
	@ $(MAKE) -f $(SIMV_DIR)/Makefile run
	@ rm -f rcdname.cfg


ifeq (n,$(findstring n,$(firstword -$(MAKEFLAGS))))
# not run with -n / --dry-run
define shell_or_print
  $(info $(1))
endef
else
# run with -n / --dry-run
define shell_or_print
  $(shell $(1))
endef
endif

## targets 'clean' & 'virgin' - special handling
# We ensure that clean/virgin are always executed before any other target
# This enables proper execution of e.g. 'make clean diff'

# clean: removes most generated files
ifneq ($(filter clean virgin,$(MAKECMDGOALS)),)
  # diffs, logfiles
  $(call shell_or_print,rm -f *.diff *.gdbdiff *.rtldiff *.ocddiff *.gdbocddiff *.oscidiff *.gdboscidiff *.oscicppdiff *.vpdiff *.log *.err)
  # chess_report files
  $(call shell_or_print,rm -f  *.mem *.gcc)
  # HDL simulation related files
  $(call shell_or_print,rm -f ucli.key appname.cfg rcdname.cfg rtlsim.cycle_count *.saif)
  # compilation results
  $(call shell_or_print,rm -rf Release/ Native/ Debug/ Release_LLVM*/ Debug_LLVM*/)
  # VCS related files
  $(call shell_or_print,rm -rf INCA_libs ucli.key DVEfiles inter.vpd data.bin novas.conf verdiLog)
  # Virtualizer related files
  $(call shell_or_print,rm -rf analysis_results/ T32/ work.*/)
endif

# virgin: removes even more
ifneq ($(filter virgin,$(MAKECMDGOALS)),)
  # per-app GUI preferences
  $(call shell_or_print,rm -f *.prxui)
  # make.all message files
  $(call shell_or_print,rm -f .message*)
  # files containing port numbers of running simulations
  $(call shell_or_print,rm -f ISS_RPC_SERVER_PORT* JTS_PORT_NUMBER*)
endif

clean:
	@ echo -n ""

virgin:
	@ echo -n ""

reset:
	chessmk -r -C $(CFG) test.prx

.PHONY: help native ok chess clean virgin reset updateprx
.PHONY: run issrun rtlrun saifrun ocdrun gdbrun gdbocdrun saifrun vprun oscirun gdboscirun oscicpprun
.PHONY: diff rtldiff ocddiff gdbdiff gdbocddiff vpdiff oscidiff gdboscidiff oscicppdiff
.PHONY: hex rtlgui rtlfree genexitfile

.FORCE: ;
